<?php

/**
 * Implements hook_ting_client_webservice (@see ting_client.module)
 * */
function bibdk_borchk_ting_client_webservice() {
  $ret = array();
  $ret['borchk']['class'] = 'bibdk_borchk';
  $ret['borchk']['url'] = 'bibdk_borchk_url';
  return $ret;
}

function bibdk_borchk_netpunkt_request($userid, $agency,$outputType = 'json', $serviceRequester = 'netpunkt'){
  // this is the real request

  $params = array(
    'action' => 'borrowerCheckRequest',
    'userId' => $userid,
    'serviceRequester' => $serviceRequester,
    'libraryCode' => $agency,
    'outputType' => $outputType,
  );

  if (module_exists('ting_client')) {
    $response = ting_client_do_request('borchk', $params);
  }
  else {
    $client = new ting_client_class();
    $response = $client->do_request('borchk',$params);
  }
  return $response;
}

/**
 * do a request
 * */
function bibdk_borchk_request($userId, $userPincode, $libraryCode, $outputType = 'json', $serviceRequester = NULL) {
  if(empty($serviceRequester)){
    $serviceRequester = variable_get('bibdk_borchk_servicerequester');
  }

  $params = array(
    'action' => 'borrowerCheckRequest',
    'userId' => $userId,
    'userPincode' => $userPincode,
    'serviceRequester' => $serviceRequester,
    'libraryCode' => $libraryCode,
    'outputType' => $outputType,
  );

  if (module_exists('ting_client')) {
    $response = ting_client_do_request('borchk', $params);
  }
  else {
    // this is the real request
    $client = new ting_client_class();
    $response = $client->do_request('borchk', $params);
  }
  return $response;
}

/**
 * Implements hook_form_FORM_ID_alter (ting_client_admin_webservices_settings)
 * add 2 fields to webservice client settings
 * @url to borchk
 * @servicerequester
 * */
function bibdk_borchk_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state) {
  // don't start by defining the fieldset as an array. This way other modules can extend the fieldset.
  $form['borchk']['#type'] = 'fieldset';
  $form['borchk']['#title'] = t('borchk settings');
  $form['borchk']['#description'] = t('Client for borchk, a service for verifiying users against library endpoints.');
  $form['borchk']['#collapsible'] = TRUE;
  $form['borchk']['#collapsed'] = TRUE;
  $form['borchk']['#tree'] = FALSE;

  $form['borchk']['bibdk_borchk_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Borchk URL'),
    '#description' => t('URL to borchk e.g.  http://borchk.addi.dk/2.3/'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_borchk_url', FALSE),
  );
  $form['borchk']['bibdk_borchk_servicerequester'] = array(
    '#type' => 'textfield',
    '#title' => t('Service requester parameter for borchk'),
    '#description' => t('the default service requester (if no other given) e.g. bibliotek.dk'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_borchk_servicerequester', FALSE),
  );
}

/**
 * Implements hook_how_r_u()
 * @return Array
 */
function bibdk_borchk_how_r_u() {
  return array('Borchk' => variable_get('bibdk_borchk_url'));
}
